// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD0aT77Az2wNpci4Ekr2rbT4Z7XOphD1s',
    appId: '1:803362916765:web:b435d0efd0c1a17a6f8774',
    messagingSenderId: '803362916765',
    projectId: 'praktik-firebase-database',
    authDomain: 'praktik-firebase-database.firebaseapp.com',
    databaseURL: 'https://praktik-firebase-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'praktik-firebase-database.firebasestorage.app',
    measurementId: 'G-SMTYG4XTEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUcc3S8q083xdQtsSDeCq7jVwc3Z1hdA',
    appId: '1:803362916765:android:eefa27aaee5bc3f36f8774',
    messagingSenderId: '803362916765',
    projectId: 'praktik-firebase-database',
    databaseURL: 'https://praktik-firebase-database-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'praktik-firebase-database.firebasestorage.app',
  );
}
